services:

  # ── Nó 1 – primário ─────────────────────────────────────────────
  rabbit1:
    image: rabbitmq:3.13-management
    hostname: rabbit1
    container_name: rabbit1
    environment:
      RABBITMQ_ERLANG_COOKIE: "TP01_SECRET_COOKIE"
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5672:5672"
      - "15672:15672"   # Management UI
    volumes:
      - rabbit1_data:/var/lib/rabbitmq
    networks:
      - rabbitmq_net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  # ── Nó 2 ────────────────────────────────────────────────────────
  rabbit2:
    image: rabbitmq:3.13-management
    hostname: rabbit2
    container_name: rabbit2
    environment:
      RABBITMQ_ERLANG_COOKIE: "TP01_SECRET_COOKIE"
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - rabbit2_data:/var/lib/rabbitmq
    networks:
      - rabbitmq_net
    depends_on:
      rabbit1:
        condition: service_healthy

  # ── Nó 3 ────────────────────────────────────────────────────────
  rabbit3:
    image: rabbitmq:3.13-management
    hostname: rabbit3
    container_name: rabbit3
    environment:
      RABBITMQ_ERLANG_COOKIE: "TP01_SECRET_COOKIE"
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5674:5672"
      - "15674:15672"
    volumes:
      - rabbit3_data:/var/lib/rabbitmq
    networks:
      - rabbitmq_net
    depends_on:
      rabbit1:
        condition: service_healthy

  # ── PostgreSQL ───────────────────────────────────────────────────
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: tp01
      POSTGRES_PASSWORD: tp01pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - rabbitmq_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tp01 -d ecommerce"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  rabbitmq_net:
    driver: bridge

volumes:
  rabbit1_data:
  rabbit2_data:
  rabbit3_data:
  postgres_data: